// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLaunchers() {
  return window['go']['app']['App']['GetLaunchers']();
}

export function GetLibrary() {
  return window['go']['app']['App']['GetLibrary']();
}

export function LaunchGame(arg1, arg2, arg3) {
  return window['go']['app']['App']['LaunchGame'](arg1, arg2, arg3);
}
