// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetAccounts():Promise<Array<models.Account>>;

export function LaunchGame(arg1:string,arg2:string):Promise<string>;
