// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAccounts() {
  return window['go']['app']['App']['GetAccounts']();
}

export function LaunchGame(arg1, arg2) {
  return window['go']['app']['App']['LaunchGame'](arg1, arg2);
}
