// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddCustomGame(arg1:string,arg2:string):Promise<string>;

export function GetLaunchers():Promise<Array<models.LauncherGroup>>;

export function GetLibrary():Promise<Array<models.LibraryGame>>;

export function LaunchGame(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SelectExe():Promise<string>;

export function SwitchToAccount(arg1:string,arg2:string):Promise<string>;
