// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddCustomGame(arg1:string,arg2:string):Promise<string>;

export function AddTorrentGame(arg1:string,arg2:string):Promise<string>;

export function DeleteAccount(arg1:string,arg2:string):Promise<string>;

export function EpicCheckStatus():Promise<boolean>;

export function EpicInstallGame(arg1:string):Promise<string>;

export function EpicLaunchGame(arg1:string):Promise<string>;

export function EpicLogin(arg1:string):Promise<string>;

export function EpicLogout():Promise<void>;

export function GetEpicGames():Promise<Array<models.GameUI>>;

export function GetEpicLibrary():Promise<Array<models.GameUI>>;

export function GetLaunchers():Promise<Array<models.LauncherGroup>>;

export function GetLibrary():Promise<Array<models.LibraryGame>>;

export function LaunchEpicGame(arg1:string):Promise<void>;

export function LaunchGame(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function LoginLegendaryAccount():Promise<string>;

export function RemoveGame(arg1:string,arg2:string):Promise<string>;

export function SaveEpicAccount(arg1:string):Promise<string>;

export function SaveLegendaryAccount(arg1:string):Promise<string>;

export function SaveRiotAccount(arg1:string):Promise<string>;

export function SelectExe():Promise<string>;

export function SelectImage():Promise<string>;

export function SetGameImage(arg1:string,arg2:string):Promise<string>;

export function SwitchEpicAccount(arg1:string):Promise<string>;

export function SwitchLegendaryAccount(arg1:string):Promise<string>;

export function SwitchToAccount(arg1:string,arg2:string):Promise<string>;

export function ToggleGameAccountHidden(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ToggleGamePin(arg1:string):Promise<string>;

export function UpdateAccountData(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function UpdateGameNote(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;
