// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomGame(arg1, arg2) {
  return window['go']['app']['App']['AddCustomGame'](arg1, arg2);
}

export function GetLaunchers() {
  return window['go']['app']['App']['GetLaunchers']();
}

export function GetLibrary() {
  return window['go']['app']['App']['GetLibrary']();
}

export function LaunchGame(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['LaunchGame'](arg1, arg2, arg3, arg4);
}

export function SelectExe() {
  return window['go']['app']['App']['SelectExe']();
}
